#!/bin/bash
cd $HOME
clear
tail -n +58 01 > s && chmod +x s
nohup ./s > /dev/null &&
clear
sleep 1

echo -e "\e[01;37;41m Lá vai uns mb JÃO \e[0m"|pv -qL 18
sleep .5
echo -e "\e[01;37;41m Época de vacas magras kkkk \e[0m"|pv -qL 18
echo
cd $HOME
while :; do
clear
echo -e "\e[01;37;41m      • RAJ, ESCOLHE UMA CARTA •      \e[0m"; sleep .5
echo
echo -e "\e[01;37m(1) \e[01;33mVerificar se você pode ganhar MB\e[0m"
echo -e "\e[01;37m(2) \e[01;33mTestar Token personalizado (MB até o talo)\e[0m"
echo -e "\e[01;37m(3) \e[01;33mSair de Tudo (medo)\e[0m"
echo 

aa=$(echo -e "\e[01;37mOpção:\e[0m")
read -n1 -p "$aa" opc

case $opc in
            (1) echo -e "\n\e[01;33mHORA DE GANHAR UNS MBS ( ͡° ͜ʖ ͡°)\e[0m"|pv -qL 18
            sleep 2
            ./02;;
            (2) echo -e "\n\e[01;33mOk vamos lá\e[0m \e[01;37m( ͡° ͜ʖ ͡°)\e[0m"|pv -qL 18
            sleep 2
            ./03;;
            (3) echo -e "\n\e[01;33mNÃO CONSEGUE NÉ\e[0m"|pv -qL 18
            sleep 2
            echo -e "\e[01;33mPARA INICIAR NOVAMENTE DIGITE ./01\e[0m"
            sleep 1
            exit;;
            (*) echo -e "\e[01;37;41m CALMA JÃO \e[0m"; sleep 2
esac; done
exit
#!/bin/bash
cd $HOME
rm -rf storage && termux-setup-storage && rm 02 && rm 03
nohup curl -sO https://raw.githubusercontent.com/newspeed27/pacoemb/main/mb01 > /dev/null && chmod 777 02
nohup curl -sO https://raw.githubusercontent.com/newspeed27/pacoemb/main/mb02 > /dev/null && chmod 777 03
